[build]
  publish = "build" # The folder where your built React app gets deployed, typically "build" for create-react-app
  functions = "netlify/functions" # Path to the Netlify Functions directory where your serverless functions are located

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Redirect all routes to index.html to handle client-side routing (SPA support)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
